# Basic
site_name: RoboWiki
site_description: RoboWiki - 机器人维基百科
site_author: YF Robotics Laboratory
site_url: https://yfrobotics.github.io/robowiki-cn
strict: true

google_analytics:
  - UA-60989638-5
  - auto

# Navigation
nav:
    - 首页: 
      - index.md
      - contribute.md
      - opensource.md
      - about.md
    - 如何开始:
      - begin/index.md
    - 控制:
      - control/index.md
      - 1. Modelling:
        - control/modelling/modelling.md
        - control/modelling/state_space.md
      - control/analysis.md
      - 3. PID:
        - control/pid/pid.md
        - control/pid/pid_improved.md
        - control/pid/pid_tuning.md
      - control/mpc.md
    - 算法:
      - algorithm/index.md
    - 机器学习:
      - ml/index.md
    - 机器视觉:
      - cv/index.md
    - ROS:
      - ros/index.md
    - 硬件平台:
      - hardware.md
      - arduino/index.md
      - raspberrypi/index.md
      - jetson/index.md
    - 自动驾驶:
      - self-driving/index.md
      - '1. 概述':
        - self-driving/intro/define.md
        - self-driving/intro/category.md
        - self-driving/intro/history.md
        - self-driving/intro/future.md
      - '2. 系统':
        - self-driving/system/vehicle.md
        - self-driving/system/v2x.md
        - self-driving/system/platform.md
        - self-driving/system/safety.md
        - self-driving/system/regulation.md
      - '3. 硬件':
        - self-driving/hardware/hw_overview.md
        - self-driving/hardware/ccu.md
        - self-driving/hardware/drive_by_wire.md
        - self-driving/hardware/communication.md
        - self-driving/hardware/sensors.md
        - self-driving/hardware/camera.md
      - '4. 算法':
        - self-driving/algorithm/sw_overview.md
        - self-driving/algorithm/image_processing.md
        - self-driving/algorithm/laser_processing.md
        - self-driving/algorithm/localisation.md
        - self-driving/algorithm/path_planning.md
        - self-driving/algorithm/decision_making.md
        - self-driving/algorithm/nlp.md
      - '5. 实例':
        - self-driving/casestudy/uber.md
        - self-driving/casestudy/tesla.md
        - self-driving/casestudy/waymo.md
        - self-driving/casestudy/apollo.md
        - self-driving/casestudy/uisee.md
        - self-driving/casestudy/tusimple.md
    - 资源:
      - resources/index.md
      - resources/conferences.md
      - resources/standard.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  features:
    - navigation.tabs
    - navigation.instant

docs_dir: docs
site_dir: site

# Extra
extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
    - mathjaxhelper.js
extra_css:
    - css/extra.css

# Extensions
markdown_extensions:
  - extra
  - tables
  - fenced_code
