# Site Configurations
site_name: 机器人中文维基 (RoboWiki-cn)
site_description: 机器人领域知识库
site_author: YunFei Robotics Laboratory
site_url: https://wiki.yfworld.com
strict: false

docs_dir: docs
site_dir: site

# Google Analytics
google_analytics:
  - UA-60989638-5
  - auto

# Navigation
nav:
    - 首页: 
      - index.md
      - how-to-contribute.md
      - contributors.md
      - about.md
    - “如何”系列:
      - how-to/main.md
      - how-to/how-to-start.md
    - 控制:
      - control/index.md
      - 1. Modelling:
        - control/modelling/modelling.md
        - control/modelling/state_space.md
      - 2. Analysis: control/analysis.md
      - 3. PID:
        - control/pid/pid.md
        - control/pid/pid_improved.md
        - control/pid/pid_tuning.md
      - 4. MPC: control/mpc.md
    - 算法:
      - algorithm/index.md
    - 自动驾驶:
      - self-driving/index.md
      - '1. 概述':
        - self-driving/intro/main.md
        - self-driving/intro/define.md
        - self-driving/intro/category.md
        - self-driving/intro/history.md
        - self-driving/intro/future.md
      - '2. 系统':
        - self-driving/system/main.md
        - self-driving/system/vehicle.md
        - self-driving/system/v2x.md
        - self-driving/system/platform.md
        - self-driving/system/safety.md
        - self-driving/system/regulation.md
      - '3. 硬件':
        - self-driving/hardware/main.md
        - self-driving/hardware/hw_overview.md
        - self-driving/hardware/ccu.md
        - self-driving/hardware/drive_by_wire.md
        - self-driving/hardware/communication.md
        - self-driving/hardware/sensors.md
        - self-driving/hardware/camera.md
      - '4. 算法':
        - self-driving/algorithm/main.md
        - self-driving/algorithm/sw_overview.md
        - self-driving/algorithm/image_processing.md
        - self-driving/algorithm/laser_processing.md
        - self-driving/algorithm/localisation.md
        - self-driving/algorithm/path_planning.md
        - self-driving/algorithm/decision_making.md
        - self-driving/algorithm/nlp.md
      - '5. 实例':
        - self-driving/casestudy/main.md
        - self-driving/casestudy/uber.md
        - self-driving/casestudy/tesla.md
        - self-driving/casestudy/waymo.md
        - self-driving/casestudy/apollo.md
        - self-driving/casestudy/uisee.md
        - self-driving/casestudy/tusimple.md
    - 硬件平台:
      - hardware.md
      - arduino/index.md
      - raspberrypi/index.md
      - jetson/index.md
    - 资源:
      - resources/index.md
      - resources/simulators.md
      - resources/conferences.md
      - resources/standard.md
      - resources/competitions.md
      - resources/labs.md
      - resources/materials.md
      - resources/tools.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  logo: "logo-site.png"
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Extra
extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
  - _static/js/mathjaxhelper.js

extra_css:
    - _static/css/extra.css

# Extensions
markdown_extensions:
  - admonition
  - extra
  - tables
  - fenced_code
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
