# Site Configurations
site_name: "机器人中文维基"
site_description: 机器人领域的公共知识库
site_author: "YFRL"
site_url: https://wiki.yfworld.com
strict: false

# Repository
repo_name: 'yfrobotics/robowiki-cn'
repo_url: 'https://github.com/yfrobotics/robowiki-cn'
edit_uri: ''

docs_dir: docs
site_dir: site

# Google Analytics
google_analytics:
  - UA-60989638-5
  - auto

# Navigation
nav:
    - 首页: 
      - 简介: index.md
      - how-to-contribute.md
      - standard.md
      - contributors.md
    - 入门:
      - basic/intro.md
    - 建模:
      - modelling/intro.md
    - 控制: 
      - 机器人控制: control/index.md
      - 控制系统建模:
        - control/modelling/modelling.md
        - control/modelling/state_space.md
      - PID控制:
        - control/pid/pid.md
        - control/pid/pid_improved.md
        - control/pid/pid_tuning.md
      - MPC控制: control/mpc/mpc.md
    - 传感:
      - 机器人传感: sensing/index.md
    - 规划:
      - 机器人规划: planning/index.md
    - 视觉:
      - 机器视觉: cv/index.md
    - 仿真:
        机器人仿真: simulation/simulators.md
    - Linux:
      - Linux: linux/index.md
    - ROS:
      - ROS: ros/index.md
    - FreeRTOS:
      - FreeRTOS: freertos/index.md
    - 硬件:
      - 机器人硬件平台: hardware/index.md
      - arduino/index.md
      - raspberrypi/index.md
      - jetson/index.md
    - 资源:
      - 机器人资源: resources/index.md
      - resources/conferences.md
      - resources/standard.md
      - resources/competitions.md
      - resources/labs.md
      - resources/materials.md
      - resources/software.md
    - <自动驾驶>:
      - 自动驾驶技术指南: self-driving/index.md
      - '1. 概述':
        - self-driving/intro/main.md
        - self-driving/intro/define.md
        - self-driving/intro/category.md
      - '2. 系统':
        - self-driving/system/main.md
        - self-driving/system/vehicle.md
        - self-driving/system/v2x.md
        - self-driving/system/platform.md
        - self-driving/system/safety.md
        - self-driving/system/regulation.md
      - '3. 硬件':
        - self-driving/hardware/main.md
        - self-driving/hardware/hw_overview.md
        - self-driving/hardware/ccu.md
        - self-driving/hardware/drive_by_wire.md
        - self-driving/hardware/communication.md
        - self-driving/hardware/sensors.md
        - self-driving/hardware/camera.md
      - '4. 算法':
        - self-driving/algorithm/main.md
        - self-driving/algorithm/sw_overview.md
        - self-driving/algorithm/image_processing.md
        - self-driving/algorithm/laser_processing.md
        - self-driving/algorithm/localisation.md
        - self-driving/algorithm/path_planning.md
        - self-driving/algorithm/decision_making.md
        - self-driving/algorithm/nlp.md
      - '5. 实例':
        - self-driving/casestudy/main.md
        - self-driving/casestudy/apollo.md


# Theme
theme:
  name: 'material'
  language: 'zh'
  logo: "logo-site.png"
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: false
  search_index_only: true
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Extra
extra_javascript:
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
  - _static/js/mathjaxhelper.js

extra_css:
    - _static/css/extra.css

# Extensions
markdown_extensions:
  - admonition
  - extra
  - tables
  - fenced_code
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
