# Site Configurations
site_name: "机器人中文维基"
site_description: 机器人领域的公共知识库
site_author: "YFRL"
site_url: https://wiki.yfworld.com
strict: false

# Repository
repo_name: 'yfrobotics/robowiki-cn'
repo_url: 'https://github.com/yfrobotics/robowiki-cn'
edit_uri: ''

docs_dir: docs
site_dir: site

# Google Analytics
google_analytics:
  - UA-60989638-5
  - auto

# Navigation
nav:
    - 首页: 
      - index.md
      - how-to-contribute.md
      - standard.md
      - contributors.md
    - 入门:
      - basics/intro.md
      - basics/courses.md
      - basics/books.md
    - 控制: 
      - control/index.md
      - control/control-theory-diagram.md
      - 控制系统建模:
        - control/modelling/modelling.md
        - control/modelling/state-space.md
      - PID控制:
        - control/pid/pid.md
        - control/pid/pid-improved.md
        - control/pid/pid-tuning.md
      - MPC控制: 
        - control/mpc/mpc.md
    - 感知:
      - sensing/index.md
      - sensing/sensors.md
      - sensing/cv.md
    - 规划:
      - planning/index.md
      - planning/pathplanning.md
      - planning/motionplanning.md
      - planning/decisionmaking.md
    - 仿真:
      - simulation/index.md
      - simulation/gazebo.md
      - simulation/vrep.md
      - simulation/mujoco.md
      - simulation/pybullet.md
      - simulation/webots.md
      - simulation/robotics-toolbox.md
      - simulation/stage.md
    - ROS:
      - ros/index.md
      - ros/ros1.md
      - ros/ros2.md
    - Linux:
      - linux/index.md
    - RTOS:
      - rtos/index.md
    - 硬件:
      - hardware/index.md
      - arduino/index.md
      - raspberrypi/index.md
      - jetson/index.md
    - 数据库:
      - database/index.md
      - database/boston-dynamics.md
    - 资源:
      - resources/index.md
      - resources/conferences.md
      - resources/standard.md
      - resources/competitions.md
      - resources/labs.md
      - resources/companies.md
      - resources/software.md

# Theme
# Document: https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
theme:
  name: 'material'
  language: 'zh'
  logo: "logo-site.png"
  palette:
    primary: 'white'
    accent: 'red'
  include_search_page: true
  search_index_only: true
  features:
    - navigation.tabs
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Extensions
markdown_extensions:
  - admonition
  - extra
  - tables
  - fenced_code
  - mdx_math

# Extra
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS_HTML

extra_css:
    - _static/css/extra.css
